Consider the below code to answer further questions:

```
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```


**Question 1** Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

**Answer** Yes, there is a difference in the data type of the variables list_ and array_list.

list_ is a Python list containing strings.

array_list is a NumPy array containing strings.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [3]:
print("Data type of list_:", type(list_))

print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


**Question2** Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

**Answer**

In [4]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Question - 3** Considering the following changes in the variable, array_list:

```array_list = np.array(object = list_, dtype = int)```

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

**Answer**

In [7]:
array_list = np.array(object=list_, dtype=int)

In [8]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:
```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```


**Question4** Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size


In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
print("Shape of num_array:", num_array.shape)

Shape of num_array: (2, 3)


In [12]:
print("Size of num_array:", num_array.size)

Size of num_array: 6


**Question 5 :** Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.


In [13]:
import numpy as np
zero_matrix = np.zeros((3, 3))

print("3x3 matrix of zeros:")
print(zero_matrix)

3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Question 6** Create an identity matrix of shape (5,5) using numpy functions?

In [14]:
import numpy as np

identity_matrix = np.eye(5)

print("5x5 identity matrix:")
print(identity_matrix)


5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
